force-app/main/default/objects/Contact/fields/Dia__c.field-meta.xml
<CustomField>
    <fullName>Dia__c</fullName>
    <formula>DAY( Birthdate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CumpleShudulerClassTest.cls
@IsTest
public class CumpleShudulerClassTest {

     @TestSetup
     static void makeData(){
         
        List<Contact> contatc = new List<Contact>();
        for (Integer i = 0; i < 10; i++) {
            contatc.add(new Contact(Salutation = 'Mr', FirstName = 'Pablo', LastName='Flores', Email = 'mego@gmail.com', Birthdate= date.today()));
        }
          Database.insert(contatc);

        
         

     }
     
     static testmethod void sendEmailTest(){
        
        List<Contact> listcont = Database.query('SELECT Id , Mes__c, Dia__c FROM Contact');
        CumpleShudulerClass cumple = new CumpleShudulerClass();
        cumple.execute(SC);
     }
     
    
}